Layout/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Layout.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            return View();
        }

        public ActionResult Services()
        {
            ViewBag.Message = " goo";
                return View();
        }


        public ActionResult Contact()
        {
            ViewBag.Message = "";
            return View();
        }


    }
}

Layout/Controllers/OyunlarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Layout.Models;

namespace Layout.Controllers
{
    public class OyunlarsController : Controller
    {
        private OyunSiteEntities db = new OyunSiteEntities();

        
        public ActionResult Index(String SearchString)
        {
           var oyunara = from u in db.Oyunlars
                         join b in db.Kategoris on u.kategoriID equals b.kategoriID
                         select u;
                 if (!string.IsNullOrEmpty(SearchString))
        {
               oyunara = from u in db.Oyunlars
                         join b in db.Kategoris on u.kategoriID equals b.kategoriID
                         where (b.KategoriAd.ToUpper().Contains(SearchString.ToUpper()))
                    select u;
         }
           return View(oyunara);
        }

      
            public ActionResult Index1()
            {
            var kategori = from u in db.Oyunlars
                           join b in db.Kategoris on u.kategoriID equals b.kategoriID
                           where b.KategoriAd.Contains("yar")
                           select u;
                           
            return View(kategori);
            }

        public ActionResult Index2()
        {
            var kategori = from u in db.Oyunlars
                           join b in db.Kategoris on u.kategoriID equals b.kategoriID
                           where b.KategoriAd.Contains("spor")
                           select u;

            return View(kategori);
        }

        public ActionResult Index3()
        {
            var kategori = from u in db.Oyunlars
                           join b in db.Kategoris on u.kategoriID equals b.kategoriID
                           where b.KategoriAd.Contains("aksiyon")
                           select u;

            return View(kategori);
        }

        public ActionResult Index4()
        {
            var kategori = from u in db.Oyunlars
                           join b in db.Kategoris on u.kategoriID equals b.kategoriID
                           where b.KategoriAd.Contains("macera")
                           select u;

            return View(kategori);
        }



        // GET: Oyunlars/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oyunlar oyunlar = db.Oyunlars.Find(id);
            if (oyunlar == null)
            {
                return HttpNotFound();
            }
            return View(oyunlar);
        }

        public ActionResult Details1(int id = 17)
        {
            Oyunlar oyunlar = db.Oyunlars.Find(id);
            return View(oyunlar);


        }
        public ActionResult Details2(int id = 16)
        {
            Oyunlar oyunlar = db.Oyunlars.Find(id);
            return View(oyunlar);


        }
        public ActionResult Details3(int id = 14)
        {
            Oyunlar oyunlar = db.Oyunlars.Find(id);
            return View(oyunlar);


        }
        public ActionResult Details4(int id = 15)
        {
            Oyunlar oyunlar = db.Oyunlars.Find(id);
            return View(oyunlar);


        }
        public ActionResult Details5(int id = 13)
        {
            Oyunlar oyunlar = db.Oyunlars.Find(id);
            return View(oyunlar);
        }



        // GET: Oyunlars/Create
        public ActionResult Create()
        {
            ViewBag.kategoriID = new SelectList(db.Kategoris, "kategoriID", "KategoriAd");
            return View();
        }

        // POST: Oyunlars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OyunID,OyunDili,PlatformAd,SistemGereksinimleri,OyunUcreti,OyunHikaye,OyunAd,kategoriID")] Oyunlar oyunlar)
        {
            if (ModelState.IsValid)
            {
                db.Oyunlars.Add(oyunlar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.kategoriID = new SelectList(db.Kategoris, "kategoriID", "KategoriAd", oyunlar.kategoriID);
            return View(oyunlar);
        }

        // GET: Oyunlars/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oyunlar oyunlar = db.Oyunlars.Find(id);
            if (oyunlar == null)
            {
                return HttpNotFound();
            }
            ViewBag.kategoriID = new SelectList(db.Kategoris, "kategoriID", "KategoriAd", oyunlar.kategoriID);
            return View(oyunlar);
        }

        // POST: Oyunlars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OyunID,OyunDili,PlatformAd,SistemGereksinimleri,OyunUcreti,OyunHikaye,OyunAd,kategoriID")] Oyunlar oyunlar)
        {
            if (ModelState.IsValid)
            {
                db.Entry(oyunlar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.kategoriID = new SelectList(db.Kategoris, "kategoriID", "KategoriAd", oyunlar.kategoriID);
            return View(oyunlar);
        }

        // GET: Oyunlars/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oyunlar oyunlar = db.Oyunlars.Find(id);
            if (oyunlar == null)
            {
                return HttpNotFound();
            }
            return View(oyunlar);
        }

        // POST: Oyunlars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Oyunlar oyunlar = db.Oyunlars.Find(id);
            db.Oyunlars.Remove(oyunlar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Layout/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<div class="container">
    <div class="row">
        <div class="col-md-5">


            <h2>@ViewBag.Title.</h2>
            <h3>@ViewBag.Message</h3>

            <p>Use this area to provide additional information.</p>
        </div>
       </div>
   </div>

Layout/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Hazırlayanlar";
}
<div class="container">
    <div class="row">
        <div class="col-md-5">


            <h2>@ViewBag.Title.</h2>
            <h3>@ViewBag.Message</h3>
            <p>
               Ad: Yüksel Yumrutaş 
            </p>
            <p>
                No: 1521012075
            </p>
            <p>
                Ad: Bahar Şapçı 
            </p>
            <p>
                No: 1211016041
            </p>
            <p>
                Ad: 
            </p>
            <p>
                No: 
            </p>
            


            

        </div>
    </div>
</div>

Layout/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Indexx";

}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <p class="lead">Kategoriler</p>
            <div class="list-group-item-heading>
                <p>
                <a href="#" class="list">@Html.ActionLink("Yarış", "Index1", "Oyunlars")</a>
                </p>
               
                 <p>
                    <a href="#" class="list">@Html.ActionLink("Spor", "Index2", "Oyunlars")</a>
                </p>

                <p>
                    <a href="#" class="list">@Html.ActionLink("Aksiyon", "Index3", "Oyunlars")</a>
                </p>
                <p>
                    <a href="#" class="list">@Html.ActionLink("Macera", "Index4", "Oyunlars")</a>
                </p>
            </div>
        </div>
        <div class="col-md-9">
            <div class="row carousel-holder">
                <div class="col-md-12">
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="slide-image" src="https://i2.wp.com/thecrazyinfo.com/wp-content/uploads/2017/07/maxresdefault4.jpg?resize=800%2C300" alt="">
                            </div>
                            <div class="item">
                                <img class="slide-image" src="http://www.game-refraction.com/wp-content/uploads/2017/07/Crossout-5-800x300.png" alt="">
                            </div>
                            <div class="item">
                                <img class="slide-image" src="http://globalweet.com/wp-content/uploads/2017/06/Why-is-gta-game-so-popular-in-the-modern-trend.jpg" alt="">
                            </div>
                        </div>
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="http://2.bp.blogspot.com/-MIye2MD8iQY/Vq3alqDn96I/AAAAAAAAILU/ZAOgwewJEvM/s320/LEGO%2BMarvel%2BSuper%2BHeroes%2BPC%2BGame.jpg" alt="">
                        <div class="caption">
                            <h4 class="pull-right">₺30.00</h4>
                            <h4>
                                <a href="#" class="list">@Html.ActionLink("Lego Marvel", "Details1", "Oyunlars")</a>
                            </h4>
                            
                        </div>
                        <div class="ratings">
                            <p class="pull-right">15 reviews</p>
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="https://2.bp.blogspot.com/-XCh3E17rSIo/WV1qBY0VvvI/AAAAAAAAGyU/kGVGF5CUtQIEas5UEybLfKFotNmTk1MHACLcBGAs/s320/ss.png" alt="">
                        <div class="caption">
                            <h4 class="pull-right">₺79.00</h4>
                            <h4>
                                <a href="#" class="list">@Html.ActionLink("MotoGP17", "Details2", "Oyunlars")</a>
                            </h4>
                            
                        </div>
                        <div class="ratings">
                            <p class="pull-right">12 reviews</p>
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="http://apkgamescrak.com/wp-content/uploads/2016/06/ARK-Survival-Evolved-320x150.jpg" alt="">
                        <div class="caption">
                            <h4 class="pull-right">₺99.00</h4>
                            <h4>
                                <a href="#" class="list">@Html.ActionLink("ARK", "Details3", "Oyunlars")</a>
                            </h4>
                           
                        </div>
                        <div class="ratings">
                            <p class="pull-right">31 reviews</p>
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>

                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="http://apkgamescrak.com/wp-content/uploads/2015/02/322-320x150.jpg" alt="">
                        <div class="caption">
                            <h4 class="pull-right">₺29.00</h4>
                            <h4>
                                <a href="#" class="list">@Html.ActionLink("Wipe Out", "Details4", "Oyunlars")</a>
                            </h4>
                           
                        </div>
                        <div class="ratings">
                            <p class="pull-right">6 reviews</p>
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="https://3.bp.blogspot.com/-_ltaMn2v7B0/VrdTadvEA_I/AAAAAAAAIR0/rVOutzluvZk/s320/American%2BTruck%2BSimulator%2BPC%2BGame.jpg" alt="">
                        <div class="caption">
                            <h4 class="pull-right">₺59.00</h4>
                            <h4>
                                <a href="#" class="list">@Html.ActionLink("American Truck", "Details5", "Oyunlars")</a>
                            </h4>
                            
                        </div>
                        <div class="ratings">
                            <p class="pull-right">18 reviews</p>
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-md-4">
                    
                </div>
            </div>
        </div>
    </div>
</div>

Layout/Views/Home/Services.cshtml
@{
    ViewBag.Title = "Services";
}
<div class="container">
    <div class="row">
        <div class="col-md-5">


            <h2>@ViewBag.Title.</h2>
            <h3>@ViewBag.Message</h3>

            <p>Use this area to provide additional information.</p>
        </div>
    </div>
</div>